default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages: [pre-commit]
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cd backend && cargo fmt --check'
        language: rust
        files: ^backend/
        types_or: [rust, toml]
      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cd backend && cargo clippy --verbose'
        language: rust
        files: ^backend/
        types_or: [rust, toml]
      - id: cargo-build
        name: cargo build
        entry: bash -c 'cd backend && cargo build'
        language: rust
        files: ^backend/
        types_or: [rust, toml]
      - id: cargo-test
        name: cargo test
        entry: bash -c 'cd backend && cargo test --verbose'
        language: rust
        files: ^backend/
        types_or: [rust, toml]
      - id: bun-install
        name: bun install
        entry: bash -c 'cd frontend && bun install'
        language: node
        files: ^frontend/
        types_or: [javascript, ts, svelte, json]
      - id: bun-lint
        name: bun run lint
        entry: bash -c 'cd frontend && bun run lint'
        language: node
        files: ^frontend/
        types_or: [javascript, ts, svelte, json]
      - id: bun-check
        name: bun run check
        entry: bash -c 'cd frontend && bun run check'
        language: node
        files: ^frontend/
        types_or: [javascript, ts, svelte, json]
      - id: bun-test
        name: bun run test
        entry: bash -c 'cd frontend && bun run test'
        language: node
        files: ^frontend/
        types_or: [javascript, ts, svelte, json]
